export enum Categories{
  CALIDAD = 'CALIDAD',
  GESTION_HUMANA = 'GESTION HUMANA',
  COMERCIAL = 'COMERCIAL',
  FINANCIERA ='FINANCIERA',
  MANTENIMIENTO ='MANTENIMIENTO',
  DIRECCION = 'DIRECCION',
  OPERACION_LOGISTICA = 'OPERACION_LOGISTICA',
  PREPARADOS_ESTERILES = 'PREPARADOS_ESTERILES',
  DISTRIBUCION_MEDICAMENTOS ='DISTRIBUCION_MEDICAMENTOS'
}